const food = [
  {
    id: 1,
    name: 'Cheeseburger',
    description: 'Nice grilled burger with cheese',
    price: 8.5,
  },
  {
    id: 2,
    name: 'Fries',
    description: 'Fried french fries',
    price: 2.5,
  },
]

const dessert = [
  {
    id: 3,
    name: 'Vanilla ice cream',
    description: 'Ice cream',
    price: 2,
  },
]

const drinks = [
  {
    id: 4,
    name: 'Coca-Cola',
    price: 1.75,
  },
  {
    id: 5,
    name: 'Fanta',
    price: 1.5,
  },
  {
    id: 6,
    name: 'Sprite',
    price: 1.5,
  },
]

export const restaurants = [
  {
    id: '1',
    name: "'n Sterk Staaltje",
    mapsUrl: 'https://goo.gl/maps/EnyNcNJtvC3QkFgJ6',
    url: 'https://www.sterkstaaltje.com/',
    address: 'Staalstraat 12 1011 JL Amsterdam',
    specialty: 'Truffelworst (truffle sausage)',
    photoUrl:
      'https://media-cdn.tripadvisor.com/media/photo-s/18/1a/96/54/main-restaurant.jpg',
    categories: ['comfort-food'],
    isNew: true,
    menu: {
      food,
      dessert,
      drinks,
    },
  },
  {
    id: '2',
    name: 'Kara Fin',
    mapsUrl: 'https://goo.gl/maps/M5wMk7oKUn5BWWtp7',
    url: 'http://www.karafirin.nl/',
    address: 'Tijnmuiden 5F 1046 AK Amsterdam',
    specialty: 'Sarma (wine leafs with rice)',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['burgers', 'pizza'],
    menu: {
      food,
      dessert,
      drinks,
    },
  },
  {
    id: '3',
    name: 'De Oliewinkel',
    mapsUrl: 'https://goo.gl/maps/cpjHq1mNPGqWELFC9',
    url: 'https://deoliewinkelamsterdam.nl/',
    address: 'Brouwersgracht 119 1015 GD Amsterdam',
    specialty: 'Olive oil',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['comfort-food'],
    menu: {
      food,
      dessert,
      drinks,
    },
    isClosed: true,
  },
  {
    id: '4',
    name: "'t Kuyltje",
    mapsUrl: 'https://goo.gl/maps/C5HXbGpa2qKuKshq7',
    url: 'https://www.kuyltje.nl/',
    address: 'GASTHUISMOLENSTEEG 9 1016 AM AMSTERDAM',
    specialty: 'Pastrami sandwiches',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['comfort-food'],
    isNew: true,
    menu: {
      food,
      dessert,
      drinks,
    },
  },
  {
    id: '1',
    name: 'Ciao Bella',
    mapsUrl: 'https://g.page/ciaobellaamsterdam?share',
    url: 'http://ciaobellaamsterdam.nl/',
    address: 'Prinsengracht 1055/H 1017JE Amsterdam',
    specialty: 'Takeaway lasagna',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['pizza'],
    isNew: true,
    menu: {
      food,
      dessert,
      drinks,
    },
  },
  {
    id: '1',
    name: 'Soup Eno',
    mapsUrl: 'https://goo.gl/maps/KRoR7xfUDKZMPLqV8',
    url: 'https://soupenzo.nl/',
    address: 'Nieuwe Spiegelstraat 54',
    specialty: 'Spinach soup',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['asian'],
    menu: {
      food,
      dessert,
      drinks,
    },
  },
  {
    id: '1',
    name: 'Warung Atika',
    mapsUrl: 'https://goo.gl/maps/RidH93JHj9SuNrKFA',
    url: 'https://www.warungatika.nl/',
    address: 'Van Woustraat 232 1073 NC Amsterdam',
    specialty:
      '€6 meals (especially the yellow rice + oerap oerap + tempeh combo)',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['sushi', 'asian'],
    menu: {
      food,
      dessert,
      drinks,
    },
  },
  {
    id: '1',
    name: "Yuan's Hot Pot",
    mapsUrl: 'https://g.page/yuanhotpot',
    url: 'https://yuanhotpot.com/',
    address: 'Rijnstraat 51,1078PZ Amsterdam',
    specialty: 'cheap and fun evening meals',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['thai'],
  },
  {
    id: '1',
    name: 'Coffee Concepts',
    mapsUrl: 'https://goo.gl/maps/GpXoBRC76c9UtE5G7',
    url: 'https://www.coffeeconcepts.co/',
    address: 'Jacob Obrechtstraat 5 1071 KC Amsterdam',
    specialty: 'Chicken Avocado sandwich',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'A-Fusion',
    mapsUrl: 'https://goo.gl/maps/sYrVRMFTYRYsdJTn8',
    url: 'https://a-fusion.nl/',
    address: 'Zeedijk 130, 1012 BC Amsterdam',
    specialty: 'Surprise menu',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'BAK',
    mapsUrl: 'https://g.page/BAKRESTAURANT',
    url: 'https://bakrestaurant.nl/en/',
    address: 'Van Diemenstraat 408, 1013 CR Amsterdam',
    specialty: 'expensive dinners',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['indian'],
  },
  {
    id: '1',
    name: 'FOER',
    mapsUrl: 'https://g.page/foer-amsterdam',
    url: 'http://foeramsterdam.nl/',
    address: 'Cruquiusweg 9, 1019 AT Amsterdam',
    specialty: 'expensive dinners',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['comfort-food'],
    menu: {
      food,
      dessert,
      drinks,
    },
  },
  {
    id: '1',
    name: 'Van Stapele Koekmakerij',
    mapsUrl: 'https://goo.gl/maps/Lcwi2ByDxPtfA8C2A',
    url: 'http://www.vanstapele.com/',
    address: 'Heisteeg 4, 1012 WC Amsterdam',
    specialty: 'cookies',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['indian', 'comfort-food'],
  },
  {
    id: '1',
    name: "Trattoria That's Amore",
    mapsUrl: 'https://g.page/trattoria-that-s-amore?share',
    url: 'http://www.trattoriathatsamore.nl/',
    address: 'Vijzelgracht 17, 1017 HM Amsterdam',
    specialty: 'Linguini with seafood',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Onigiri YA!',
    mapsUrl: 'https://g.page/onigiriya?share',
    url: 'https://www.onigiriya.eu/',
    address: 'Ferdinand Bolstraat 37, 1072 LB Amsterdam',
    specialty: 'Onigiri',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Caldi e freddi',
    mapsUrl: 'https://goo.gl/maps/TySB4DTKQmvtxUNE6',
    url: 'http://www.caldiefreddi.nl/',
    address: 'Spuistraat 102, 1012 VA Amsterdam',
    specialty:
      'an extremely affordable Italian traiteur who do the basic dishes, and some great sandwiches for 3.50.',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Rotisserie East',
    mapsUrl: 'https://goo.gl/maps/xGpNXzM76RFqqLJM8',
    url: 'http://www.rotisserieamsterdam.nl/',
    address: 'Beukenplein 17, 1092 BA Amsterdam',
    specialty: 'burgers',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'nNea Pizza',
    mapsUrl: 'https://goo.gl/maps/B1eUdCx98mb5HAFm6',
    url: 'http://www.nneapizza.com/',
    address: 'Bilderdijkstraat 92, 1053 KX Amsterdam',
    specialty: 'pizza',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Massimo Gelato',
    mapsUrl: 'https://www.facebook.com/Massimo-IJsfabriek-1782424235336639',
    url: 'https://g.page/massimogelatoamsterdam?share',
    address: 'Van Ostadestraat 147 H, 1072 SW Amsterdam',
    specialty: 'gelato',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Mooie Boules Amsterdam',
    mapsUrl: 'https://g.page/mooieboulesamsterdam?share',
    url: 'http://www.mooieboules.nl/',
    address: 'Zeeburgerpad 3, 1018 AJ Amsterdam',
    specialty: 'burritos ',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Eddy Spaghetti',
    mapsUrl: 'https://goo.gl/maps/QeUgWNwTR8yVxVuU9',
    url: 'http://www.eddyspaghetti.nl/',
    address: 'Krugerplein 23, 1092 KA Amsterdam',
    specialty: 'pizza ',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Kauffmann - Falafel & Beer',
    mapsUrl: 'https://g.page/barkauffmann?share',
    url: 'http://barkauffmann.nl/',
    address: 'Reinier Claeszenstraat 4b, 1056 WJ Amsterdam',
    specialty: 'Falafel ',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Broodje Bert',
    mapsUrl: 'https://goo.gl/maps/vh7DH2Zs3QXUMnpi6',
    url: 'https://nl-nl.facebook.com/pages/Broodje-Bert/202804973064874',
    address: 'Singel 321, 1012 WK Amsterdam',
    specialty: 'sandwiches. Cash only',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Ramen-Kingdom',
    mapsUrl: 'https://goo.gl/maps/VVn6UhTEQieBG4Sv5',
    url: 'https://www.facebook.com/RamenKingdom/',
    address: 'Prins Hendrikkade 83H, 1012 AE Amsterdam',
    specialty: 'the best vegetarian ramen',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'FuLu Mandarijn',
    mapsUrl: 'https://goo.gl/maps/qya2qkTcVJbEJPJZ8',
    url: 'http://www.fulumandarijn.com/',
    address: 'Rokin 26, 1012 KS Amsterdam',
    specialty: 'the most authentic Chinese food',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Ken Sushi',
    mapsUrl: 'https://goo.gl/maps/EGEAMRvN3VCMwtU48',
    url:
      'https://kensushiamsterdam.business.site/?utm_source=gmb&utm_medium=referral',
    address: 'Lootsstraat 5, 1053 NT Amsterdam',
    specialty: 'sushi',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Kaiko',
    mapsUrl: 'https://goo.gl/maps/NV7jVZ36Z81xkAFB9',
    url: 'https://nl-nl.facebook.com/pages/Kaiko/197107776993589',
    address: 'Jekerstraat 114, 1078 MJ Amsterdam',
    specialty: 'sushi',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Men Impossible',
    mapsUrl: 'https://g.page/MenImpossible?share',
    url:
      'https://men-impossible.business.site/?utm_source=gmb&utm_medium=referral',
    address: 'Hazenstraat 19H, 1016 SM Amsterdam',
    specialty: 'the best ramen (also vegan but it’s impossible to tell)',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Umaimon',
    mapsUrl: 'https://goo.gl/maps/3ppSGNCD1TLT7vvK7',
    url: 'https://www.umaimonramennoodle.nl/',
    address: 'Korte Leidsedwarsstraat 51, 1017 PW Amsterdam',
    specialty: 'black garlic ramen',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Koreaans-Japans Restaurant NAMU',
    mapsUrl: 'https://goo.gl/maps/mfxBw7ovaiwCDLtv5',
    url: 'https://www.facebook.com/pages/Namu/722902831095513',
    address: 'Kostverlorenhof 54, 1183 HG Amstelveen',
    specialty: 'Korean food',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Hwa Won',
    mapsUrl: 'https://goo.gl/maps/g5QYkqhUA4k9Q6EQ7',
    url: 'http://www.instagram.com/hwawon_amsterdam',
    address: 'Nederhoven 13, 1082 AM Amsterdam',
    specialty: 'Korean food',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Bhatti Pasal - Authentic Nepalese Food',
    mapsUrl: 'https://goo.gl/maps/ogF4jYmDx6RDgRqw9',
    url: 'https://www.bhattipasal.nl/',
    address: 'Voetboogstraat 23, 1012 XK Amsterdam',
    specialty: 'Nepalese food',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Franggo De Pijp',
    mapsUrl: 'https://g.page/letsgofranggo?share',
    url: 'http://www.franggo.nl/',
    address: 'Eerste Sweelinckstraat 9h, 1073 CK Amsterdam',
    specialty: 'peri peri chicken',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Zoet & Hartig Haarlemmerdijk',
    mapsUrl: 'https://g.page/zoetenhartigamsterdam?share',
    url: 'https://www.amsterdamcakes.nl/',
    address: 'Haarlemmerdijk 158, 1013 JK Amsterdam',
    specialty: 'red velvet cake',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Los Pilones',
    mapsUrl: 'https://goo.gl/maps/6DgxaW8PNW41PHw29',
    url: 'http://www.lospilones.com/',
    address: 'Kerkstraat 59/63, 1017 GC Amsterdam',
    specialty: 'margaritas in a pitcher',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Hoi Tin',
    mapsUrl: 'https://goo.gl/maps/NMnbXwrWRYwAnnWaA',
    url: 'http://www.restauranthoitin.com/nl/aboutus.php',
    address: 'Zeedijk 122, 1012 BB Amsterdam',
    specialty: 'dim sum and old school Cantonese dishes',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Thúskomme',
    mapsUrl: 'https://goo.gl/maps/6F73WB1fUbyhVtTK9',
    url: 'https://thuskomme.nl/',
    address: 'Batjanstraat 1A, 1094 RC Amsterdam',
    specialty: 'Frisian restaurant, have a great selection of booze',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'BAR JOOST',
    mapsUrl: 'https://goo.gl/maps/Y4eofzqpvYF5xNF99',
    url: "http://joost-amsterdam.nl/'",
    address: 'Molukkenstraat 33, 1095 AT Amsterdam',
    specialty: 'Great everything',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Tigris En Eufraat',
    mapsUrl: 'https://goo.gl/maps/zCjSNCpKWK7Jc17t9',
    url: 'https://www.tigriseneufraat.nl/',
    address: 'Javastraat 20H, 1094 HH Amsterdam',
    specialty: 'chicken shoarma',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Sonny',
    mapsUrl: 'https://goo.gl/maps/JPXgEQH7sjPptF9s8',
    url: 'http://www.sonnyfalafel.nl/',
    address: 'Eerste van der Helststraat 43, 1073 AC Amsterdam',
    specialty: 'Falafel',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'La Fucina',
    mapsUrl: 'https://goo.gl/maps/47pHYVVJRv1iPgpa9',
    url: 'http://www.lafucina.nl/',
    address: 'Javastraat 99, 1094 HC Amsterdam',
    specialty: 'traditional Italian',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Black Gold Amsterdam',
    mapsUrl: 'https://goo.gl/maps/7nFyiC8gqWcCjwUn6',
    url: 'http://www.blackgoldamsterdam.com/',
    address: 'Korte Koningsstraat 13 H, 1011 EX Amsterdam',
    specialty: 'great coffee (filter or espresso) AND your LP needs',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Toko Man Li Ho',
    mapsUrl: 'https://goo.gl/maps/oPod3gn2xJGdmBkv6',
    url: 'https://www.facebook.com/ManLiHoJavastraat/',
    address: 'Javastraat 21, 1094 GX Amsterdam',
    specialty: 'Chinese/Surinaams sandwiches',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Eatmosfera Oost',
    mapsUrl: 'https://goo.gl/maps/z4s3GJkcCmbU7G4LA',
    url: 'http://www.eatmosfera.nl/',
    address: 'Sumatrastraat 47, 1094 LN Amsterdam',
    specialty: 'the best pizza in town',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'De Jonge Admiraal',
    mapsUrl: 'https://goo.gl/maps/M8yw3afMoZz5bp2A9',
    url: 'http://www.dejongeadmiraal.nl/',
    address: 'Javastraat 149, 1094 HE Amsterdam',
    specialty: 'a slice of carrot cake and a coffee',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Bar Fisk',
    mapsUrl: 'https://goo.gl/maps/UZfBGzfTimNvQyrTA',
    url: 'http://www.barfisk.nl/',
    address: 'Eerste Sweelinckstraat 23, 1073 CL Amsterdam',
    specialty: 'seafood and great cocktails',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Japans restaurant ISSHIN',
    mapsUrl: 'https://g.page/isshin-japanese-restaurant?share',
    url: 'https://www.instagram.com/isshin_amsterdam/?hl=en',
    address: 'Frans Halsstraat 38h, 1072 BS Amsterdam',
    specialty: 'in Amstelveen for the best ramen',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'En Japanese kitchen & Sake bar',
    mapsUrl: 'https://g.page/en-japanese-kitchen-sake-bar?share',
    url: 'http://www.en-amsterdam.nl/',
    address: 'Dusartstraat 53 h, 1072 HP Amsterdam',
    specialty: 'the best sake menu and the best f Japanese food in town',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'The Bab',
    mapsUrl: 'https://goo.gl/maps/8Cp8r8yRQ4jt7njBA',
    url: 'http://www.thebab.company/',
    address: 'Camperstraat 36, 1091 AG Amsterdam',
    specialty: 'great Korean fried chicken',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'The Meets',
    mapsUrl: 'https://g.page/themeetsoost?share',
    url: 'http://www.themeets.nl/',
    address: 'Sumatrastraat 28, 1094 ND Amsterdam',
    specialty: 'great for my vegan and gluten intolerant peeps',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Broodje Popov',
    mapsUrl: 'https://goo.gl/maps/DL2WzynsF2yYw4Zc9',
    url: 'http://broodjepopov.nl/',
    address: 'Van Woustraat 20, 1073 LL Amsterdam',
    specialty: 'Broodje pekelvlees',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'My little Patisserie',
    mapsUrl: 'https://goo.gl/maps/cnJmnUtLCBNjm5W19',
    url: 'http://my-little-patisserie.com/',
    address: 'Eerste van der Helststraat 63 HS, 1073 AD Amsterdam',
    specialty: 'Éclairs',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Tjins Toko',
    mapsUrl: 'https://goo.gl/maps/guBh7FBFQFwstNg19',
    url: 'http://www.tjinstoko.eu/',
    address: 'Eerste van der Helststraat 64, 1072 NZ Amsterdam',
    specialty: 'Portie pom ',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Romios Griekse Traiteur',
    mapsUrl: 'https://goo.gl/maps/Kr2DixTyo8wKQauH9',
    url: 'http://www.romios.nl/',
    address: 'Ceintuurbaan 350, 1072 GP Amsterdam',
    specialty: 'Olive oil and other delicacies',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'World of Food',
    mapsUrl: 'https://goo.gl/maps/B4L5UoLHQRvm2evW9',
    url: 'http://www.worldoffoodamsterdam.nl/',
    address: 'Develstein 100, 1102 AK Amsterdam-Zuidoost',
    specialty: 'Fufu, pastechi, sateh',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Roopram Roti',
    mapsUrl: 'https://goo.gl/maps/L3FAFHSVJ7sErjJn8',
    url: 'http://www.roopramroti.nl/',
    address: 'Eerste Van Swindenstraat 4, 1093 GC Amsterdam',
    specialty: 'Roti ',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'De Drie Graefjes',
    mapsUrl: 'https://goo.gl/maps/EdrzKaA2bdjy52ZG8',
    url: 'http://www.dedriegraefjes.nl/',
    address: 'dam en, Rokin 130, 1012 LD Amsterdam',
    specialty: 'Red Velvet cake',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Winkel 43',
    mapsUrl: 'https://goo.gl/maps/4NibCvJeQKyy6Ck1A',
    url: 'http://www.winkel43.nl/',
    address: 'Noordermarkt 43, 1015 NA Amsterdam',
    specialty: 'Apple Pie',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Patisserie Tout',
    mapsUrl: 'https://goo.gl/maps/gPzCX6MpsEXL8xFTA',
    url: 'https://toutpatisserie.nl/',
    address: 'Maasstraat 77, 1078 HE Amsterdam',
    specialty: 'French patisserie (especially macarons)',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Lalla Rookh',
    mapsUrl: 'https://goo.gl/maps/FRC8qUtrqmQPKWnT9',
    url: 'http://www.lalla-rookh.nl/',
    address: 'Wijttenbachstraat 290, 1093 JK Amsterdam',
    specialty: 'Pom meal',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Falafel by Sir Hummus',
    mapsUrl: 'https://g.page/Falafel-by-Sir-Hummus?share',
    url: 'http://sirhummus.nl/',
    address: 'Ruysdaelkade 181, 1072 AT Amsterdam',
    specialty: 'Falafel',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Pacomer Caterer',
    mapsUrl: 'https://goo.gl/maps/xz2R9P1pYvMfJSVA9',
    url: 'http://www.pacomertraiteur.nl/',
    address: 'Gerard Doustraat 66, 1072 VV Amsterdam',
    specialty: 'Pallela (5€!)',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Sham Restaurant',
    mapsUrl: 'https://goo.gl/maps/YPcc2eLwkwZTKbHn7',
    url: 'https://shamrestaurant.nl/',
    address: 'Warmoesstraat 36H, 1012 JE Amsterdam',
    specialty: 'Syrian Kebab',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Patisserie Holtkamp',
    mapsUrl: 'https://goo.gl/maps/X12JHFwBLHbFudj16',
    url: 'https://www.patisserieholtkamp.nl/',
    address: 'Vijzelgracht 15, 1017 HM Amsterdam',
    specialty: 'Kroket',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'New King',
    mapsUrl: 'https://goo.gl/maps/Kq6pKdo3JpHtHY6p7',
    url: 'http://www.newking.nl/',
    address: 'Zeedijk 115-117, 1012 AV Amsterdam',
    specialty: 'Chinese restaurant',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Broodje Daan',
    mapsUrl: 'https://goo.gl/maps/xAcuFxjVXEvgQgUu5',
    url: 'http://www.broodjedaan.nl/',
    address: 'Jan van Galenstraat 219, 1056 BW Amsterdam',
    specialty:
      'voetbalkantine vibe with affordable sandwiches that come with names from the people that work there',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Seoul Food',
    mapsUrl: 'https://goo.gl/maps/dcXBEbE1SWZGx9x1A',
    url: 'http://www.seoulfoodamsterdam.nl/',
    address: 'Kinkerstraat 73A, 1053 DG Amsterdam',
    specialty: 'take away korean shop',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Monks Coffee Roasters.',
    mapsUrl: 'https://g.page/Monks-Coffee-Roasters?share',
    url: 'http://monkscoffee.nl/',
    address: 'Bilderdijkstraat 46, 1052 NB Amsterdam',
    specialty: 'coffee ',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'De Pasteibakkerij',
    mapsUrl: 'https://goo.gl/maps/aw4TxrtHH9uFMPcQA',
    url: 'http://www.depasteibakkerij.nl/',
    address: 'Hoendiepstraat 2, 1079 LT Amsterdam',
    specialty: 'Fresh bacon',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Wil Graanstra Friteshuis',
    mapsUrl: 'https://goo.gl/maps/ZHKdCZU6VyVRZzvd8',
    url: 'https://www.facebook.com/Wil-Graanstra-Frites-186189854753526/',
    address: 'Westermarkt 11, 1016 DH Amsterdam',
    specialty: 'French fries',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Restaurant éénvistwéévis Amsterdam',
    mapsUrl: 'https://g.page/amsterdam-restaurant?share',
    url: 'http://www.eenvistweevis.nl/',
    address: 'Schippersgracht 6I, 1011 TR Amsterdam',
    specialty: 'Crayfish soup',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Ibericus Amsterdam',
    mapsUrl: 'https://goo.gl/maps/MJc1cV2JWBRT4QWb7',
    url: 'https://www.facebook.com/IbericusAmsterdam/info',
    address: 'Haarlemmerstraat 93, 1013 EP Amsterdam',
    specialty: 'Cured Spanish ham',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Salvatorica',
    mapsUrl: 'https://g.page/Salvatorica?share',
    url: 'http://salvatorica.com/',
    address: 'Lijnbaansgracht 71, 1015 GX Amsterdam',
    specialty: 'Handmade pasta',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Margherita Tutta La Vita',
    mapsUrl: 'https://goo.gl/maps/CJ9DkebAFYXyo4Kg9',
    url: 'http://www.margheritapizza.nl/',
    address: 'Dalsteindreef 2040, 1112 XC Diemen',
    specialty: 'Pizza margherita',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'De Oranjerie',
    mapsUrl: 'https://goo.gl/maps/qVy1Nribh4L7BP8w6',
    url: 'https://facebook.com/CafeDeOranjerie/',
    address: 'Binnen Oranjestraat 15hs, 1013 HZ Amsterdam',
    specialty: 'Lamb burger',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'De Avondmarkt',
    mapsUrl: 'https://goo.gl/maps/z5RbpB9DCMTkys8M7',
    url: 'http://www.deavondmarkt.nl/',
    address: 'De Wittenkade 90-96, 1051 AK Amsterdam',
    specialty: 'Coconut bon bons',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Effendy Bakery & Cafe',
    mapsUrl: 'https://g.page/effendybakery?share',
    url: 'https://www.facebook.com/EffendyBakeryCafe/',
    address: 'Rozengracht 148, 1016 NJ Amsterdam',
    specialty: 'the BEST Turkish pizza for like €4.50',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Slagerij De Leeuw',
    mapsUrl: 'https://goo.gl/maps/tdYTE53Zs379aeVH8',
    url: 'http://www.slagerijdeleeuw.nl/',
    address: 'Utrechtsestraat 92, 1017 VS Amsterdam',
    specialty: 'proper guanciale',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Vlaams Friteshuis Vleminckx',
    mapsUrl: 'https://goo.gl/maps/SXwewJpKCHP8aMwV6',
    url: 'http://vleminckxdesausmeester.nl/',
    address: 'Voetboogstraat 33, 1012 XK Amsterdam',
    specialty: 'patat',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Little Collins',
    mapsUrl: 'https://g.page/LittleCollinsdePijp?share',
    url: 'http://www.littlecollins.nl/',
    address: 'Eerste Sweelinckstraat 19F, 1073 CL Amsterdam',
    specialty: 'amazing food and the best coffee',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Eetsalon Van Dobben',
    mapsUrl: 'https://goo.gl/maps/3tauwM71oNUZMdNo6',
    url: 'http://www.eetsalonvandobben.nl/',
    address: 'Korte Reguliersdwarsstraat 5-7-9, 1017 BH Amsterdam',
    specialty: 'Broodje filet americain Broodje kroket Broodje halfom',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'La Perla Pizzeria',
    mapsUrl: 'https://goo.gl/maps/fSiviUntaQi5LsqE8',
    url: 'http://pizzaperla.nl/',
    address: 'Tweede Tuindwarsstraat 53, 1015 RZ Amsterdam',
    specialty: 'pizza ',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Mythos Greek Restaurant',
    mapsUrl: 'https://goo.gl/maps/dDzy7WDVf2dHn2cD9',
    url: 'http://mythosgreek.nl/',
    address: 'Lange Leidsedwarsstraat 27, 1017 NG Amsterdam',
    specialty: 'Greek food ( esp. Souvlaki gyros)',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'FuLu Mandarijn',
    mapsUrl: 'https://goo.gl/maps/4ZoyoBZgzbWVuyH9A',
    url: 'http://www.fulumandarijn.com/',
    address: 'Rokin 26, 1012 KS Amsterdam',
    specialty: 'Chinese food',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Thai Curry House',
    mapsUrl: 'https://goo.gl/maps/yqDismYJ7Dbm45v59',
    url: 'https://www.thaicurryhouse.nl/',
    address: 'Willem van Weldammelaan 4, 1082 KV Amsterdam',
    specialty: "Samosa's",
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'BBROOD',
    mapsUrl: 'https://goo.gl/maps/8M1zenVJNpuRYLaq8',
    url: 'https://www.bbrood.nl/',
    address: 'Ms. van Riemsdijkweg 30, 1033 RD Amsterdam',
    specialty: 'the mais bread is amazing',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Chocolátl',
    mapsUrl: 'https://goo.gl/maps/e1UHoQiLdggqxTaj7',
    url: 'http://chocolatl.nl/',
    address: 'Hazenstraat 25-A, 1016 SM Amsterdam',
    specialty: 'Chocolate ',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Bird Thais Restaurant',
    mapsUrl: 'https://goo.gl/maps/KLY4UZnCMViPSCrR6',
    url: 'http://www.thai-bird.nl/',
    address: 'Zeedijk 72-74, 1012 BA Amsterdam',
    specialty: 'Nr.35',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Vatten Ramen Kerkstraat',
    mapsUrl: 'https://g.page/vatten-ramen-kerkstraat?share',
    url: 'http://vattenramen.com/',
    address: 'Kerkstraat 148, 1017 GR Amsterdam',
    specialty: 'chicken ramen',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Morena aan de Amstel',
    mapsUrl: 'https://goo.gl/maps/9uCKsTCWfyXJoM638',
    url: 'http://www.morena-amsterdam.nl/',
    address: 'Amstel 47, 1011 PW Amsterdam',
    specialty: 'Pita Gyros',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Warung Barokah',
    mapsUrl: 'https://goo.gl/maps/T7UP2vRpN8zmbTHS7',
    url: 'http://www.warungbarokah.nl/',
    address: 'Aalsmeerweg 91, 1059 AE Amsterdam',
    specialty: 'Indonesian, surprisingly authentic',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Bakers & Roasters',
    mapsUrl: 'https://goo.gl/maps/5wwLpCYWAeNGR4oF7',
    url: 'http://bakersandroasters.com/',
    address: 'Eerste Jacob van Campenstraat 54, 1072 BH Amsterdam',
    specialty: 'Mississippi Mud cake',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'De Bakkers Van Oost',
    mapsUrl: 'https://goo.gl/maps/7vUjrprKQ2cmMhqM8',
    url: 'https://www.debakkersvanoost.nl/',
    address: 'Sumatrastraat 42, 1094 NE Amsterdam',
    specialty: 'the kwarkballen and Klinker bread',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Il Sogno',
    mapsUrl: 'https://goo.gl/maps/6qiLcRgeoC13ffSQ8',
    url: 'http://www.il-sogno.nl/',
    address: 'IJburglaan 905, 1087 EN Amsterdam',
    specialty: 'pizza and ice cream',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Box Sociaal',
    mapsUrl: 'https://goo.gl/maps/Y8NoUHJ9qqXCihvd9',
    url: 'http://www.boxsociaal.com/',
    address: 'Plantage Middenlaan 30A, 1018 DG Amsterdam',
    specialty: 'filtered coffee and burgers',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Spirit Amsterdam',
    mapsUrl: 'https://goo.gl/maps/r1zVAj18Hv2YA1TeA',
    url: 'http://www.spiritamsterdam.nl/',
    address: 'Czaar Peterstraat 2a, 1018 PR Amsterdam',
    specialty: 'salads and roasted veggies',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Bagels & Beans',
    mapsUrl: 'https://g.page/BagelsVeemkade?share',
    url: 'http://www.bagelsbeans.nl/',
    address: 'Veemkade 368, 1019 HE Amsterdam',
    specialty: 'Matcha latte ',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Griekse Traiterie Ela!',
    mapsUrl: 'https://g.page/elatraiterie?share',
    url: 'http://www.elatraiterie.nl/',
    address: 'Jan van Galenstraat 68, 1056 CC Amsterdam',
    specialty: 'The moussaka ',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Pigs & Punch',
    mapsUrl: 'https://goo.gl/maps/A4pgFmCfJUyyaYY76',
    url: 'http://www.pigsandpunch.nl/',
    address: 'Utrechtsestraat 30a, 1017 VN Amsterdam',
    specialty: 'the ribs ',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: "Rene's croissanterie",
    mapsUrl: 'https://goo.gl/maps/CX6h6KyzXgmG4gGW6',
    url: 'http://www.renescroissanterie.nl/',
    address: 'Damstraat 20, 1012 JM Amsterdam',
    specialty: 'the best bakery',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Worst Wijncafé',
    mapsUrl: 'https://goo.gl/maps/QmWgZ8jkyuxSz9RZA',
    url: 'http://www.deworst.nl/',
    address: 'Barentszstraat 171, 1013 NM Amsterdam',
    specialty: 'Pied de Cochon',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'SORA Sapporo Ramen',
    mapsUrl: 'https://g.page/sappororamensora?share',
    url: 'https://ramensora.nl/',
    address: 'Ceintuurbaan 49, 1072 HR Amsterdam',
    specialty: 'Great shoyu and tonkotsu ramen',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Restaurant I-Grec',
    mapsUrl: 'https://goo.gl/maps/uWZGnbCtf83sg7ZcA',
    url: 'http://www.restaurantigrec.nl/',
    address: 'Jean Desmetstraat 121, 1087 DH Amsterdam',
    specialty: 'Authethic greek food',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Warung Spang Makandra',
    mapsUrl: 'https://goo.gl/maps/gsdftbWPiYwSqVgd8',
    url: 'https://www.spangmakandra.nl/',
    address: 'Boerhaaveplein 3, 1091 DH Amsterdam',
    specialty: 'Cheap surinam food. Sauto soup',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Dumplings',
    mapsUrl: 'https://goo.gl/maps/XGVZuoe3amF9bCuq5',
    url: 'http://dumplings-chinese.nl/',
    address: 'Nassauplein 60, 1052 AH Amsterdam',
    specialty: 'Dumplings',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Hummus bistro d&a',
    mapsUrl: 'https://goo.gl/maps/7EagfKzkoT6xsqRS7',
    url: 'https://dna-hummusbistro.com/',
    address: 'Westerstraat 136, 1015 MP Amsterdam',
    specialty: 'the best Mediterranean food',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Moeders',
    mapsUrl: 'https://g.page/restaurantmoeders?share',
    url: 'http://www.moeders.com/',
    address: 'Rozengracht 251, 1016 SX Amsterdam',
    specialty: "delicious 'traditional dutch' food",
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'AN',
    mapsUrl: 'https://goo.gl/maps/AU3aVWeqfTkfnC8y5',
    url: 'http://www.japansrestaurantan.nl/',
    address: 'Weteringschans 76, 1017 XR Amsterdam',
    specialty: 'Homestyle Japanese',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Walia ibex',
    mapsUrl: 'https://goo.gl/maps/6Tbw4tiEst1XQ5qq6',
    url: 'http://www.restaurantwaliaibex.nl/',
    address: 'Eerste Jacob van Campenstraat 41, 1072 BD Amsterdam',
    specialty: 'Ethiopian food and sharing platters',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'YamYam Trattoria Pizzeria',
    mapsUrl: 'https://g.page/YamYamTrattoriaPizzeria?share',
    url: 'http://www.yamyam.nl/',
    address: 'Frederik Hendrikstraat 88-90, 1052 HZ Amsterdam',
    specialty: 'Pizza',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Puccini Bomboni',
    mapsUrl: 'https://goo.gl/maps/kE7BumJEnfL69H8BA',
    url: 'http://www.puccinibomboni.com/',
    address: 'Staalstraat 17, 1011 JK Amsterdam',
    specialty: 'Chocolate',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Uncle Lee',
    mapsUrl: 'https://g.page/unclelee-slingelandtplein?share',
    url: 'http://www.unclelee.nl/',
    address: 'Van Slingelandtplein 7, 1051 DD Amsterdam',
    specialty: 'Korean Fried Chicken',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Gangnam Chicken',
    mapsUrl: 'https://g.page/Gangnam_Chicken_Amsterdam?share',
    url: 'http://www.gangnamchicken.nl/',
    address: 'Eerste Helmersstraat 251h, 1054 DX Amsterdam',
    specialty: 'Korean Fried Chicken',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Restaurant Daarbaand',
    mapsUrl: 'https://goo.gl/maps/AVRTgB9xho27Dw857',
    url: 'http://www.irandaarbaand.nl/',
    address: 'Overtoom 350, 1054 JG Amsterdam',
    specialty: 'Iranian Tapas',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'De Aardige Pers',
    mapsUrl: 'https://goo.gl/maps/rVWmw2t3e5qp5YxA9',
    url: 'http://www.aardigepers.nl/',
    address: 'Tweede Hugo de Grootstraat 13, 1052 LA Amsterdam',
    specialty: 'Best Restaurant in Amsterdam',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Şerifoğlu Café & Patisserie',
    mapsUrl: 'https://goo.gl/maps/kdjrhuBfa29S7dyr7',
    url: 'http://serifoglu.nl/',
    address: 'Slotermeerlaan 115, 1063 JN Amsterdam',
    specialty: 'Turkish Breakfast, Turkish Pastries',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: '45 Yummie Sushi & Bowls',
    mapsUrl: 'https://goo.gl/maps/2RZ4VtfnEs34LfhE7',
    url: 'https://www.facebook.com/45yummiesushibowls',
    address: 'Spaarndammerstraat 45hs, 1013 ST Amsterdam',
    specialty: 'Best afforable Sushi',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Nyonya Malay',
    mapsUrl: 'https://goo.gl/maps/exd1a4FKwjLGmgft9',
    url: 'http://www.nyonyamalaysiarest.nl/',
    address: 'Kloveniersburgwal 38 /HS, 1012 CW Amsterdam',
    specialty: 'Malaysian',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Restaurant/grillroom Pera',
    mapsUrl: 'https://goo.gl/maps/7wxZp6gaL5o1LfVx9',
    url:
      'https://www.tripadvisor.com/Restaurant_Review-g188590-d9681072-Reviews-Pera_Grillroom-Amsterdam_North_Holland_Province.html',
    address: 'Jan Evertsenstraat 86, 1056 EG Amsterdam',
    specialty: 'one of the best shoarma in town',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Choux',
    mapsUrl: 'https://goo.gl/maps/vATHDXk5EjYDRxf69',
    url: 'http://choux.nl/',
    address: 'De Ruijterkade 128, 1011 AC Amsterdam',
    specialty: 'For a fancy dinner with amazing wines',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Bar Centraal',
    mapsUrl: 'https://goo.gl/maps/5vAkze6UQmFESeCV6',
    url: 'https://www.barcentraal.nl/',
    address: 'Ten Katestraat 16, 1053 CE Amsterdam',
    specialty: 'Good wines and dishes to share',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
  {
    id: '1',
    name: 'Vegan Junk Food Bar',
    mapsUrl: 'https://goo.gl/maps/MrUddpJ1Ay5TFyj69',
    url: 'https://www.veganjunkfoodbar.com/locations/marie-heinekenplein/',
    address: 'Marie Heinekenplein 9, 1072 MH Amsterdam',
    specialty: 'Vegan/Vegatarian food',
    photoUrl: 'https://duyt4h9nfnj50.cloudfront.net/search_home/FastFood.jpg',
    categories: ['TBD'],
  },
]

const fakeApiCall = (data: any) => {
  return new Promise((resolve) => {
    const timeout = Math.random() * 150 + 150
    setTimeout(() => resolve(data), timeout)
  })
}

export const getCuratedRestaurants = () =>
  fakeApiCall(
    restaurants.filter((restaurant) => !restaurant.isClosed).slice(0, 6)
  )

export const getRestaurantById = (id: string) =>
  fakeApiCall(restaurants.find((restaurant) => id === restaurant.id))

export const getRestaurantsByCategory = (category: string) =>
  fakeApiCall(
    restaurants
      .filter((restaurant) =>
        restaurant.categories.includes(category.toLowerCase())
      )
      .sort((restaurant) => (restaurant.isClosed ? 1 : -1))
      .sort((restaurant) => (restaurant.isNew ? -1 : 1))
  )
