name: "Chromatic Web"

on: push

jobs:
  chromatic:
    name: Run Chromatic for web app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v5
        with:
          node-version: 22.x
      - name: Install dependencies
        run: yarn install
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN_APP }}
          buildCommand: yarn turbo chromatic --filter=@mealdrop/web -- --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN_APP }} --outputDir=./apps/web/storybook-static
          outputDir: ./apps/web/storybook-static